// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8qd6VYZ-AneLOdfY7SX_8V6Ew_DNNt4o',
    appId: '1:256384737416:web:db3aea89dbaecc1134ff3d',
    messagingSenderId: '256384737416',
    projectId: 'intern-dcd09',
    authDomain: 'intern-dcd09.firebaseapp.com',
    storageBucket: 'intern-dcd09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj1Dmnp1--EgACnbTFXsGxr0WUo9d63sY',
    appId: '1:256384737416:android:8ffd84b51786734434ff3d',
    messagingSenderId: '256384737416',
    projectId: 'intern-dcd09',
    storageBucket: 'intern-dcd09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKOfzHjgFzhujgBw3RZpHGev4Cl9W7wJU',
    appId: '1:256384737416:ios:b6a9421a73c4802934ff3d',
    messagingSenderId: '256384737416',
    projectId: 'intern-dcd09',
    storageBucket: 'intern-dcd09.appspot.com',
    iosClientId: '256384737416-6ru03hhuhbmalqnke7ag1gdimgd58fk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopify',
  );
}
